// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jphhjpozlcnfpywynvys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwaGhqcG96bGNuZnB5d3ludnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NjM2NjYsImV4cCI6MjA4NzIzOTY2Nn0.Vw42QSSDrcbRecbp6ZyaJu6rad9Q6JKVn22qzABJqhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});